import { ReactNode } from 'react'
import './globals.css'
import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'

import { Hero } from '@/components/Hero'
import { Profile } from '@/components/Profile'
import { SignIn } from '@/components/SignIn'
import { cookies } from 'next/headers'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const isAuthenticate = cookies().has('token')
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-gray-950 font-sans text-gray-100`}
      >
        <main className="grid grid-cols-2 min-h-screen">
          {/* esquerda */}
          <div className="relative flex flex-col items-start justify-between border-r border-white/10 px-28 py-16 overflow-hidden bg-[url(../assets/bg-stars.svg)] bg-cover">
            {/* blur */}
            <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 rounded-full blur-full h-[288px] w-[526px] bg-purple-700 opacity-50" />
            {/* stripes */}
            <div className="absolute bottom-0 right-2 top-0 w-2 bg-stripes"></div>
            {isAuthenticate ? <Profile /> : <SignIn />}
            <Hero />
          </div>

          {/* direita */}
          <div className="flex flex-col max-h-screen overflow-y-scroll bg-[url(../assets/bg-stars.svg)] bg-cover">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
